/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Payment = IDL.Record({ 'date' : Time, 'amount' : IDL.Nat });
export const PendingBalance = IDL.Record({
  'id' : IDL.Text,
  'model' : IDL.Text,
  'customerLastName' : IDL.Text,
  'customerFirstName' : IDL.Text,
  'payments' : IDL.Vec(Payment),
  'mobileNumber' : IDL.Text,
  'deposit' : IDL.Nat,
  'isPaid' : IDL.Bool,
  'productType' : IDL.Text,
  'email' : IDL.Text,
  'category' : IDL.Text,
  'salePrice' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContactStatus = IDL.Variant({
  'toCall' : IDL.Null,
  'called' : IDL.Null,
});
export const RepairRecord = IDL.Record({
  'id' : IDL.Text,
  'customerLastName' : IDL.Text,
  'contactStatus' : ContactStatus,
  'customerFirstName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'email' : IDL.Text,
  'receivedTimestamp' : Time,
  'isDelivered' : IDL.Bool,
  'quoteAmount' : IDL.Opt(IDL.Nat),
  'problemDescription' : IDL.Text,
  'deviceCategory' : IDL.Text,
  'deviceModel' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPayment' : IDL.Func([IDL.Text, IDL.Nat], [PendingBalance], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPendingBalance' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
      ],
      [PendingBalance],
      [],
    ),
  'createRepairRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
      ],
      [RepairRecord],
      [],
    ),
  'getAllPendingBalances' : IDL.Func([], [IDL.Vec(PendingBalance)], ['query']),
  'getAllRepairRecords' : IDL.Func([], [IDL.Vec(RepairRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOpenRepairRecords' : IDL.Func([], [IDL.Vec(RepairRecord)], ['query']),
  'getRepairRecord' : IDL.Func([IDL.Text], [RepairRecord], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markRepairDelivered' : IDL.Func([IDL.Text], [RepairRecord], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unmarkRepairDelivered' : IDL.Func([IDL.Text], [RepairRecord], []),
  'updateContactStatus' : IDL.Func(
      [IDL.Text, ContactStatus],
      [RepairRecord],
      [],
    ),
  'updateRepairQuote' : IDL.Func([IDL.Text, IDL.Nat], [RepairRecord], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Payment = IDL.Record({ 'date' : Time, 'amount' : IDL.Nat });
  const PendingBalance = IDL.Record({
    'id' : IDL.Text,
    'model' : IDL.Text,
    'customerLastName' : IDL.Text,
    'customerFirstName' : IDL.Text,
    'payments' : IDL.Vec(Payment),
    'mobileNumber' : IDL.Text,
    'deposit' : IDL.Nat,
    'isPaid' : IDL.Bool,
    'productType' : IDL.Text,
    'email' : IDL.Text,
    'category' : IDL.Text,
    'salePrice' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContactStatus = IDL.Variant({
    'toCall' : IDL.Null,
    'called' : IDL.Null,
  });
  const RepairRecord = IDL.Record({
    'id' : IDL.Text,
    'customerLastName' : IDL.Text,
    'contactStatus' : ContactStatus,
    'customerFirstName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'email' : IDL.Text,
    'receivedTimestamp' : Time,
    'isDelivered' : IDL.Bool,
    'quoteAmount' : IDL.Opt(IDL.Nat),
    'problemDescription' : IDL.Text,
    'deviceCategory' : IDL.Text,
    'deviceModel' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPayment' : IDL.Func([IDL.Text, IDL.Nat], [PendingBalance], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPendingBalance' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
        ],
        [PendingBalance],
        [],
      ),
    'createRepairRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
        ],
        [RepairRecord],
        [],
      ),
    'getAllPendingBalances' : IDL.Func(
        [],
        [IDL.Vec(PendingBalance)],
        ['query'],
      ),
    'getAllRepairRecords' : IDL.Func([], [IDL.Vec(RepairRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOpenRepairRecords' : IDL.Func([], [IDL.Vec(RepairRecord)], ['query']),
    'getRepairRecord' : IDL.Func([IDL.Text], [RepairRecord], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markRepairDelivered' : IDL.Func([IDL.Text], [RepairRecord], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unmarkRepairDelivered' : IDL.Func([IDL.Text], [RepairRecord], []),
    'updateContactStatus' : IDL.Func(
        [IDL.Text, ContactStatus],
        [RepairRecord],
        [],
      ),
    'updateRepairQuote' : IDL.Func([IDL.Text, IDL.Nat], [RepairRecord], []),
  });
};

export const init = ({ IDL }) => { return []; };