/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ContactStatus = { 'toCall' : null } |
  { 'called' : null };
export interface Payment { 'date' : Time, 'amount' : bigint }
export interface PendingBalance {
  'id' : string,
  'model' : string,
  'customerLastName' : string,
  'customerFirstName' : string,
  'payments' : Array<Payment>,
  'mobileNumber' : string,
  'deposit' : bigint,
  'isPaid' : boolean,
  'productType' : string,
  'email' : string,
  'category' : string,
  'salePrice' : bigint,
}
export interface RepairRecord {
  'id' : string,
  'customerLastName' : string,
  'contactStatus' : ContactStatus,
  'customerFirstName' : string,
  'mobileNumber' : string,
  'email' : string,
  'receivedTimestamp' : Time,
  'isDelivered' : boolean,
  'quoteAmount' : [] | [bigint],
  'problemDescription' : string,
  'deviceCategory' : string,
  'deviceModel' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPayment' : ActorMethod<[string, bigint], PendingBalance>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPendingBalance' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
    ],
    PendingBalance
  >,
  'createRepairRecord' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      [] | [bigint],
    ],
    RepairRecord
  >,
  'getAllPendingBalances' : ActorMethod<[], Array<PendingBalance>>,
  'getAllRepairRecords' : ActorMethod<[], Array<RepairRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOpenRepairRecords' : ActorMethod<[], Array<RepairRecord>>,
  'getRepairRecord' : ActorMethod<[string], RepairRecord>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markRepairDelivered' : ActorMethod<[string], RepairRecord>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unmarkRepairDelivered' : ActorMethod<[string], RepairRecord>,
  'updateContactStatus' : ActorMethod<[string, ContactStatus], RepairRecord>,
  'updateRepairQuote' : ActorMethod<[string, bigint], RepairRecord>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];