/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PendingBalance {
    id: string;
    model: string;
    customerLastName: string;
    customerFirstName: string;
    payments: Array<Payment>;
    mobileNumber: string;
    deposit: bigint;
    isPaid: boolean;
    productType: string;
    email: string;
    category: string;
    salePrice: bigint;
}
export type Time = bigint;
export interface RepairRecord {
    id: string;
    customerLastName: string;
    contactStatus: ContactStatus;
    customerFirstName: string;
    mobileNumber: string;
    email: string;
    receivedTimestamp: Time;
    isDelivered: boolean;
    quoteAmount?: bigint;
    problemDescription: string;
    deviceCategory: string;
    deviceModel: string;
}
export interface Payment {
    date: Time;
    amount: bigint;
}
export interface UserProfile {
    name: string;
}
export enum ContactStatus {
    toCall = "toCall",
    called = "called"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addPayment(id: string, amount: bigint): Promise<PendingBalance>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPendingBalance(id: string, category: string, productType: string, model: string, customerFirstName: string, customerLastName: string, mobileNumber: string, email: string, salePrice: bigint, deposit: bigint): Promise<PendingBalance>;
    createRepairRecord(id: string, deviceCategory: string, deviceModel: string, customerFirstName: string, customerLastName: string, mobileNumber: string, email: string, problemDescription: string, quoteAmount: bigint | null): Promise<RepairRecord>;
    getAllPendingBalances(): Promise<Array<PendingBalance>>;
    getAllRepairRecords(): Promise<Array<RepairRecord>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getOpenRepairRecords(): Promise<Array<RepairRecord>>;
    getRepairRecord(id: string): Promise<RepairRecord>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markRepairDelivered(id: string): Promise<RepairRecord>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    unmarkRepairDelivered(id: string): Promise<RepairRecord>;
    updateContactStatus(id: string, status: ContactStatus): Promise<RepairRecord>;
    updateRepairQuote(id: string, newQuote: bigint): Promise<RepairRecord>;
}
import type { ContactStatus as _ContactStatus, RepairRecord as _RepairRecord, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addPayment(arg0: string, arg1: bigint): Promise<PendingBalance> {
        if (this.processError) {
            try {
                const result = await this.actor.addPayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPayment(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPendingBalance(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: bigint, arg9: bigint): Promise<PendingBalance> {
        if (this.processError) {
            try {
                const result = await this.actor.createPendingBalance(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPendingBalance(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async createRepairRecord(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: bigint | null): Promise<RepairRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.createRepairRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg8));
                return from_candid_RepairRecord_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRepairRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg8));
            return from_candid_RepairRecord_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPendingBalances(): Promise<Array<PendingBalance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPendingBalances();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPendingBalances();
            return result;
        }
    }
    async getAllRepairRecords(): Promise<Array<RepairRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRepairRecords();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRepairRecords();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOpenRepairRecords(): Promise<Array<RepairRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenRepairRecords();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenRepairRecords();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRepairRecord(arg0: string): Promise<RepairRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getRepairRecord(arg0);
                return from_candid_RepairRecord_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRepairRecord(arg0);
            return from_candid_RepairRecord_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markRepairDelivered(arg0: string): Promise<RepairRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.markRepairDelivered(arg0);
                return from_candid_RepairRecord_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markRepairDelivered(arg0);
            return from_candid_RepairRecord_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async unmarkRepairDelivered(arg0: string): Promise<RepairRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.unmarkRepairDelivered(arg0);
                return from_candid_RepairRecord_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unmarkRepairDelivered(arg0);
            return from_candid_RepairRecord_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateContactStatus(arg0: string, arg1: ContactStatus): Promise<RepairRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContactStatus(arg0, to_candid_ContactStatus_n13(this._uploadFile, this._downloadFile, arg1));
                return from_candid_RepairRecord_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContactStatus(arg0, to_candid_ContactStatus_n13(this._uploadFile, this._downloadFile, arg1));
            return from_candid_RepairRecord_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRepairQuote(arg0: string, arg1: bigint): Promise<RepairRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRepairQuote(arg0, arg1);
                return from_candid_RepairRecord_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRepairQuote(arg0, arg1);
            return from_candid_RepairRecord_n4(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ContactStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactStatus): ContactStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_RepairRecord_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RepairRecord): RepairRecord {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerLastName: string;
    contactStatus: _ContactStatus;
    customerFirstName: string;
    mobileNumber: string;
    email: string;
    receivedTimestamp: _Time;
    isDelivered: boolean;
    quoteAmount: [] | [bigint];
    problemDescription: string;
    deviceCategory: string;
    deviceModel: string;
}): {
    id: string;
    customerLastName: string;
    contactStatus: ContactStatus;
    customerFirstName: string;
    mobileNumber: string;
    email: string;
    receivedTimestamp: Time;
    isDelivered: boolean;
    quoteAmount?: bigint;
    problemDescription: string;
    deviceCategory: string;
    deviceModel: string;
} {
    return {
        id: value.id,
        customerLastName: value.customerLastName,
        contactStatus: from_candid_ContactStatus_n6(_uploadFile, _downloadFile, value.contactStatus),
        customerFirstName: value.customerFirstName,
        mobileNumber: value.mobileNumber,
        email: value.email,
        receivedTimestamp: value.receivedTimestamp,
        isDelivered: value.isDelivered,
        quoteAmount: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.quoteAmount)),
        problemDescription: value.problemDescription,
        deviceCategory: value.deviceCategory,
        deviceModel: value.deviceModel
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    toCall: null;
} | {
    called: null;
}): ContactStatus {
    return "toCall" in value ? ContactStatus.toCall : "called" in value ? ContactStatus.called : value;
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RepairRecord>): Array<RepairRecord> {
    return value.map((x)=>from_candid_RepairRecord_n4(_uploadFile, _downloadFile, x));
}
function to_candid_ContactStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContactStatus): _ContactStatus {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContactStatus): {
    toCall: null;
} | {
    called: null;
} {
    return value == ContactStatus.toCall ? {
        toCall: null
    } : value == ContactStatus.called ? {
        called: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
